### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by acoolax** [lucavb/homebridge-hc-sr501#1]
How can I install plugin?

**Comment by lucavb** [comment]
I added a README file. I hope this helps.

**Comment by acoolax** [comment]
Thanks for readme! Now i have new problem. 
ERROR LOADING PLUGIN other_plugins:
Error: Cannot find module 'onoff'
I find this https://github.com/fivdi/onoff and install, but nothing change.

**Comment by acoolax** [comment]
Thanks for readme! now i have this problem:
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^
Error: EACCES: permission denied, open '/sys/class/gpio/export'
How to fix it?

**Comment by lucavb** [comment]
that appears to be an issue associated with the gpio module. you might want to search for answers over there. https://github.com/fivdi/onoff

However, it seems to me that maybe you did not activate the gpio pins on the raspberry pi? Maybe there is such an option. For me it used to be a long time ago.

**Comment by fivdi** [comment]
This issue is related to the permissions of the user running the application. For example, if the January 2017 version of Raspbian is installed, user pi will have access to GPIOs.
