### ISSUE TITLE
No motion detected.

### ISSUE THREAD

**Issue by SkyJohn** [lucavb/homebridge-hc-sr501#2]
I'm not sure what I'm doing wrong.

I installed the plugin and connected up my HC-SR501 to PWR, GND & GPIO24 but I'm getting no motion detection in the Home app.

**Comment by lucavb** [comment]
Make sure to follow the pin labelling as indicated in this [picture](https://www.element14.com/community/servlet/JiveServlet/previewBody/73950-102-10-339300/pi3_gpio.png) . So you want to use 2 for the second pin on the left side, rather than 3.

**Comment by SkyJohn** [comment]
I moved data jumper from GPIO24 to GPIO8 and it works fine now, not totally sure why though.
