### ISSUE TITLE
HC-SR501 not working in homebridge

### ISSUE THREAD

**Issue by VincentvanDuijn** [lucavb/homebridge-hc-sr501#3]
Hey :)

I downloaded and installed the plugin, but it is not working have the sensor connected on Pin 24 but it wont detect any thing. I have tested it with a python script and it detects motion. I bought mine sensor from Aliexpress maybe this is the issue maybe a fake HC-SR501 ?

**Comment by lucavb** [comment]
Make sure to use the correct pin. There are different naming conventions for the pins. The plugin that I am using is using the BCM schema. Assuming that you are using the wiringPi convention I'd suggest you try 19 instead. 

consider this [image](https://www.element14.com/community/servlet/JiveServlet/previewBody/73950-102-10-339300/pi3_gpio.png) use whatever number it says after GPIO.

**Comment by VincentvanDuijn** [comment]
Hey there

Thanks for the quick reply, so you mean i need to use pin 35 (gpio19)? And for the config file i need to use pinId 19? Instead of 35?

**Comment by VincentvanDuijn** [comment]
Got it to work! thanks for the advise! :D

**Comment by lucavb** [comment]
you're welcome

**Comment by c13m0n5t3r** [comment]
Hey, i use this Plugin and have problems. 
The motion sensor don’t toggle between heigh and low so the info in HomeKit is not correct. 
I show you some pictures and I hope somebody can help. 
![Image](http://i.imgur.com/eiousZW.jpg)
![Image](http://i.imgur.com/BUdW3TR.jpg)
I can’t find the problems

Thank you!

**Comment by lucavb** [comment]
Hey, try and make sure that the motion sensor is recognised correctly first. Since you are German this guide tells you what to do.
https://www.einplatinencomputer.com/raspberry-pi-pir-bewegungsmelder-ansteuern/

Also keep in mind the different mappings for the pins so make sure to use the right number.

**Comment by c13m0n5t3r** [comment]
Hi, with Python i can read The State of The Sensor correct. At The same Pin. 
I don‘t reconice The Problem.

**Comment by lucavb** [comment]
could you please post the entry you added to your homebridge configuration file?

**Comment by c13m0n5t3r** [comment]
![Image](https://i.imgur.com/EJIW3Tb.jpg)

**Comment by lucavb** [comment]
try 22 instead. you are using the wrong pin number scheme same as the previous poster.

**Comment by c13m0n5t3r** [comment]
ok thank You, i will try it tonight.
however I had it with the pin 22 tasted there however no movement determined

**Comment by c13m0n5t3r** [comment]
![Image](https://i.imgur.com/YItty5z.jpg)

problem still exists

**Comment by c13m0n5t3r** [comment]
*White = Signal

**Comment by lucavb** [comment]
you changed the pin you are using. please use the image below and use the number it says after GPIO, i.e. 4 in the case of GPIO4.

https://www.raspberrypi-spy.co.uk/wp-content/uploads/2012/06/Raspberry-Pi-GPIO-Layout-Model-B-Plus-rotated-2700x900.png

**Comment by c13m0n5t3r** [comment]
Now it work
Thank You!!!

**Comment by Memfya** [comment]
Hi! Help me please! My sr501 always triggered. I tried different GPIO. try other sr501. nothing helps :(
