### ISSUE TITLE
Sensor doesn't detect motion

### ISSUE THREAD

**Issue by silversurfer147** [lucavb/homebridge-hc-sr501#6]
Hi, I have a problem with my motion sensor HC-SR501. I have successfully added it into homebridge and also in Home app in my iPhone. In app it shows that motion sensor is ready, unfortunately it doesn't detect any motion. I have also tried different pin, but it doesn't help. Here is my config.json

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:FF:AB",
        "port": 32132,
        "pin": "034-12-120"
    }, 
"accessories" : [
    {
        "accessory" : "HC-SR501",
        "name" : "Motion Sensor",
        "pinId" : 24
    }
]
}`

However my motion sensor works, I tried it with code from this example https://electrosome.com/pir-motion-sensor-hc-sr501-raspberry-pi/ and it successfully detected motion. Could someone help me, where could be a problem? Thank you in advance.

**Comment by SkyJohn** [comment]
Which model of Raspberry Pi do you have?

**Comment by silversurfer147** [comment]
Hi, I have B+. However I think, I know where is problem. The script from link which I have posted uses number of pin which are in green circle https://www.raspberrypi-spy.co.uk/2014/07/raspberry-pi-b-gpio-header-details-and-pinout/ , but to config file of homebridge, I have to put number from name of pin (behind GPIO)

**Comment by SkyJohn** [comment]
Yes, the config requires the GPIO number.

**Comment by silversurfer147** [comment]
Great, it works :) Thank you!
