### ISSUE TITLE
Returned empty 

### ISSUE THREAD

**Issue by marmitol** [lucavb/homebridge-hc-sr501#9]
Hello.

Please help me, I've configured but it shows the following error.

5/12/2020, 22:57:36] [Motion Sensor1] Initializing HC-SR501 accessory...
[5/12/2020, 22:57:36] [Motion Sensor1] Accessory HC-SR501 returned empty set of services. Won't adding it to the bridge!

Thank.

**Comment by lucavb** [comment]
Hey, thank you for reporting for this bug :) Should be fixed with 1.0.4
